[build]
builder = "dockerfile"
dockerfilePath = "railway.dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "attendee.settings.production" }