[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "attendee.settings.production" }

# Web service configuration
[[services]]
name = "web"
dockerfile = "railway.web.dockerfile"
startCommand = "bash railway-web-start.sh"

[services.healthcheck]
path = "/health/"
port = 8000

# Worker service configuration  
[[services]]
name = "worker"
dockerfile = "railway.worker.dockerfile"
startCommand = "bash railway-worker-start.sh"